import { TextInput } from 'react-native'

export const users = [
	{
		name: 'Andrew',
		id: '1',
		image: require('./assets/drunk-images/Andrew.png'),
		profileChosen: false,
		overUnder: 7.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Brandon',
		id: '2',
		image: require('./assets/drunk-images/Brandon-2.png'),
		profileChosen: false,
		overUnder: 12.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Donovan',
		id: '3',
		image: require('./assets/drunk-images/Donovan.png'),
		profileChosen: false,
		overUnder: 5.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Duong',
		id: '4',
		image: require('./assets/drunk-images/Duong.png'),
		profileChosen: false,
		overUnder: 8,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Johnny',
		id: '5',
		image: require('./assets/drunk-images/Brandon-1.png'),
		profileChosen: false,
		overUnder: 11.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Joseph',
		id: '10',
		image: require('./assets/drunk-images/Joseph.png'),
		profileChosen: false,
		overUnder: 5.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Naren',
		id: '6',
		image: require('./assets/drunk-images/Naren.png'),
		profileChosen: false,
		overUnder: 5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Nicky',
		id: '7',
		image: require('./assets/drunk-images/Nicky.png'),
		profileChosen: false,
		overUnder: 5.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Ricky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Ricky',
		id: '8',
		image: require('./assets/drunk-images/Ricky.png'),
		profileChosen: false,
		overUnder: 6.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Robert', answer: false },
		],
	},
	{
		name: 'Robert',
		id: '9',
		image: require('./assets/drunk-images/Robert.png'),
		profileChosen: false,
		overUnder: 5.5,
		answerOne: '',
		answerTwo: '',
		overUnderAnswers: [
			{ name: 'Andrew', answer: false },
			{ name: 'Brandon', answer: false },
			{ name: 'Donovan', answer: false },
			{ name: 'Duong', answer: false },
			{ name: 'Johnny', answer: false },
			{ name: 'Joseph', answer: false },
			{ name: 'Naren', answer: false },
			{ name: 'Nicky', answer: false },
			{ name: 'Ricky', answer: false },
		],
	},
]

export const questions = [
	{
		question: 'Who will die first?',
		answerType: () => <TextInput />,
		id: '1',
	},
	{
		question: 'How many shots will ',
	},
]
